global:  # Глобальные настройки Prometheus.
  scrape_interval:     15s  # Интервал сбора метрик.
  evaluation_interval: 15s  # Интервал оценки правил.

scrape_configs:  # Конфигурации для сбора метрик.
  - job_name: 'prometheus'  # Название работы, используемое для идентификации в веб-интерфейсе Prometheus.
    static_configs:  # Статические конфигурации, которые определяют цели для сбора метрик.
      - targets: ['localhost:9090']  # Цели сбора метрик, в данном случае, локальный хост и порт Prometheus.
